### ISSUE TITLE
Lerna - single package

### ISSUE THREAD

**Issue by BogdanScherban** [BogdanScherban/Lerna-PulseTile#1]
@fzaninotto

Hi, Francois!

I returned to the Lerna issue and I want to try using approach which you suggested. I mean to use one general package instead of a lot of packages for each separate plugin, page etc.

I created new Lerna project:
https://github.com/BogdanScherban/Lerna-PulseTile

Package "pulsetile-react-admin" is located here:
https://github.com/BogdanScherban/Lerna-PulseTile/tree/master/packages/pulsetile-react-admin

Build for this package was created by the following rules:
https://github.com/BogdanScherban/Lerna-PulseTile/blob/master/packages/pulsetile-react-admin/package.json
https://github.com/BogdanScherban/Lerna-PulseTile/blob/master/packages/pulsetile-react-admin/tsconfig.json

...and located in lib/ directory.

I created project "showcase" and imported "pulsetile-react-admin" package there:
https://github.com/BogdanScherban/Lerna-PulseTile/blob/master/projects/showcase/src/App.js

But when I try to run this project (showcase) at my local machine (*npm start* inside *showcase/* directory), I get following error:
![Screenshot from 2019-07-12 18-44-21](https://user-images.githubusercontent.com/39263134/61140963-2b1fbb80-a4d5-11e9-8d2f-61977f0c2ac7.png)

As I understand the reason in image reporting, but all images are located inside the build:
https://github.com/BogdanScherban/Lerna-PulseTile/tree/master/packages/pulsetile-react-admin/lib/core/images
https://github.com/BogdanScherban/Lerna-PulseTile/tree/master/packages/pulsetile-react-admin/lib/version/images

Could you please help me with this issue?
Probably, I did something wrongly when I create a build...

**Comment by fzaninotto** [comment]
I don't know if it's related, but in the `lerna.json`, you declare the packages as 

```json
{
  "packages": [
    "packages/*",
    "versions/*"
  ],
  "version": "0.0.0"
}
```

While the packages are in fact located inside `packages` and `projects`. Lerna will fail to publish the packages in `versions` and ignore the ones in `projects`.

**Comment by fzaninotto** [comment]
When I try to run the showcase in your repo after running `yarn` in the main repository, I see many more errors about missing dependencies than what you described

<details>
  <summary>yarn start output</summary>
Failed to compile.

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Events/EventsTimeline.js
Module not found: 'vertical-timeline-component-react' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Events

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Events/EventsTimeline.js 12:42-86

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/images/ripple-foundation-logo-footer.png
Module build failed: Error: File Loader

emitFile is required from module system
 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/common/Footer.js 33:58-120

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/pages/PatientSummary/fragments/EventsTimeline.js
Module not found: 'vertical-timeline-component-react' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/pages/PatientSummary/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/pages/PatientSummary/fragments/EventsTimeline.js 10:42-86

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/images/pulsetile-logo.png
Module build failed: Error: File Loader

emitFile is required from module system
 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/pages/PatientsList/index.js 47:43-96

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js
Module not found: ../images/barCharts.png in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js 33:38-72

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js
Module not found: ../images/barChartsSelected.png in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js 34:46-88

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js
Module not found: ../images/pieCharts.png in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js 35:38-72

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js
Module not found: ../images/pieChartsSelected.png in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js 36:46-88

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js
Module not found: ../images/heatMap.png in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js 37:36-68

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js
Module not found: ../images/heatMapSelected.png in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/ChartsSelector.js 38:44-84

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/images/pulsetile-core-logo.png
Module build failed: Error: File Loader

emitFile is required from module system
 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/TopPart.js 35:48-98

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Events/fragments/Form.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Events/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Events/fragments/Form.js 42:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Procedures/fragments/Form.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Procedures/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Procedures/fragments/Form.js 39:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/TransferOfCare/fragments/Form.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/TransferOfCare/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/TransferOfCare/fragments/Form.js 42:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Vitals/fragments/Form.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Vitals/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Vitals/fragments/Form.js 41:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/images/randomPatient.png
Module build failed: Error: File Loader

emitFile is required from module system
 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/pages/PatientSummary/fragments/PhotoAndVitals.js 33:42-86

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/RespectPageHeader.js
Module not found: ../images/respect-small.png in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/RespectPageHeader.js 10:42-80

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/map/index.js
Module not found: 'google-map-react' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/map

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/map/index.js 28:41-68

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/RangeLine.js
Module not found: 'react-range/lib/index' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/RangeLine.js 27:14-46

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Vitals/fragments/ValueWithUnits.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Vitals/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Vitals/fragments/ValueWithUnits.js 28:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/AdvancedSearchDialog.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/AdvancedSearchDialog.js 39:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/ClinicalQueryDialog.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/ClinicalQueryDialog.js 39:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool/index.js
Module not found: '@react-pdf/pdfkit' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool/index.js 8:31-59

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool/index.js
Module not found: 'blob-stream' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool/index.js 9:36-58

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool/index.js
Module not found: 'brace/mode/javascript' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool/index.js 10:0-32

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool/index.js
Module not found: 'brace/theme/monokai' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/pdfTool/index.js 11:0-30

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/images/background.jpg
Module build failed: Error: File Loader

emitFile is required from module system
 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/config/theme.config.js 10:39-74

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/SummaryInformation.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/SummaryInformation.js 28:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/PersonalPreferences.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/PersonalPreferences.js 29:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/PersonalDetails.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/PersonalDetails.js 29:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/ClinicalRecommendations.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/ClinicalRecommendations.js 29:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/CapacityAndRepresentation.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/CapacityAndRepresentation.js 28:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/Involvement.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/Involvement.js 28:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/EmergencyContacts.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/EmergencyContacts.js 28:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/CliniciansSignatures.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/CliniciansSignatures.js 28:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/Confirmation.js
Module not found: 'react-redux-form' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/sections/Confirmation.js 29:25-52

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/RenderTrack.js
Module not found: 'react-range/lib/index' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/BusinessIntelligence/fragments/RenderTrack.js 7:14-46

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/fragments/RangeLine.js
Module not found: 'react-range' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/fragments/RangeLine.js 27:20-42

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/RangeLine/index.js
Module not found: 'react-range' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/RangeLine

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/RangeLine/index.js 7:20-42

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/fragments/RenderTrack.js
Module not found: 'react-range' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/fragments

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/core/common/Topbar/fragments/AdvancedUserSearch/fragments/RenderTrack.js 7:20-42

Error in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/RangeLine/RenderTrack.js
Module not found: 'react-range' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/RangeLine

 @ /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/pages/ReSPECT/fragments/RangeLine/RenderTrack.js 7:20-42

Error in /home/francois/git/Lerna-PulseTile/~/react-datepicker/dist/react-datepicker.css
Module build failed: Error: No PostCSS Config found in: /home/francois/git/Lerna-PulseTile/node_modules/react-datepicker/dist
 @ /home/francois/git/Lerna-PulseTile/~/react-datepicker/dist/react-datepicker.css 2:14-219 21:1-42:3 22:19-224

</details> 

And when I look at the first error message

> Module not found: 'vertical-timeline-component-react' in /home/francois/git/Lerna-PulseTile/packages/pulsetile-react-admin/lib/version/plugins/Events

I see that the `vertical-timeline-component-react` package is indeed missing in the `packages.json` of the `pulsetile-react-admin` package. 

So that leads me to 2 questions: 

- Why do I have more missing packages in the output than you? Could it be that you have installed some packages globally?
- Why are these packages missing?

**Comment by BogdanScherban** [comment]
@fzaninotto @tony-shannon 

Thanks, Francois!

Module "vertical-timeline-component-react" is used in PulseTile for timeline in Events plugin:
https://github.com/PulseTile/PulseTile-RA/blob/showcase/src/version/plugins/Events/EventsTimeline.js 

But besides "vertical-timeline-component-react" program also doesn't found:
1) "react-redux-form";
2) "react-range"
3) "brace/theme/monokai"
4) "google-map-react"
5) images storage

All this modules use in PulseTile and should be located inside node_modules.

I tried to repeat following commands:
```
// Install all required modules of pulsetile-react-admin and create a build
$ cd /packages/pulsetile-react-admin
$ npm install
$ npm run build

// Bootstrap Lerna
$ lerna bootstrap

// Try to start the projects/showcase
$ npm start
```

...and result is the same.

Can I forgot about something, which should be done, when we worked with Lerna?

**Comment by djhi** [comment]
> All these modules are used in PulseTile and should be located inside node_modules.

They are **used** but are not declared as dependencies. Any reason they are not declared in the `package.json` file for the `pulsetile-react-admin` project ?

**Comment by BogdanScherban** [comment]
This issue has been done.
